### ISSUE TITLE
Cant compile with gcc-6.x

### ISSUE THREAD

**Issue by ojaksch** [libretro/mame2014-libretro#10]
Built this core in march '16 while using gcc-5.x which went fine.
Today I tried to recompile using gcc-6.x but compile breaks:

src/mame/machine/slikshot.c: In member function ‘void itech8_state::vels_to_inters(UINT8, UINT8, INT8, UINT16_, UINT16_, UINT16_, UINT8_)’:
src/mame/machine/slikshot.c:262:47: error: invalid operands of types ‘__gnu_cxx::__enable_if<true, double>::__type {aka double}’ and ‘int’ to binary ‘operator<<’   *inter2 = 0x30f2e / (_27d8 + ((abs((INT8)vx) << 16) / 0x58f8c));

arch linux, gcc-Version 6.1.1 20160602 (GCC)

**Comment by Alcaro** [comment]
To fix: ((INT8)abs((INT8)vx) << 16)

or figure out why 'abs' no longer accepts integer types.

**Comment by ojaksch** [comment]
Great, thanks! Can confirm that fix is working.
