### ISSUE TITLE
Compiling mame for win without libco? 

### ISSUE THREAD

**Issue by godzil21** [libretro/mame2014-libretro#20]
Hello !

I was wondering... Can I compile this mame version for win without using the libco libraries? Fibers are not supported in C# and are giving me problems when trying to create a frontend in C#.

Thanks a lot!

**Comment by inactive123** [comment]
Pull requests are welcome.

**Comment by Alcaro** [comment]
We're aware libco is troublesome, but MAMEs internal architecture is fundamentally incompatible with libretro, so we have to hack it up like this.

As that guy said, we'd be happy to see it go, but we haven't found a sensible way to do that.

**Comment by inactive123** [comment]
Libco is no longer used now in the MAME 2014 core. I think we can safely close this now.
