### ISSUE TITLE
Segfault when opening roms from the command line without a full path

### ISSUE THREAD

**Issue by orbea** [libretro/mame2014-libretro#39]
OS: `Slackware64-current`
`RetroArch-2017.01.05_7d0824420_master-x86_64-1_git`
`mame2014-libretro-2017.01.05_7dc561f73d_master-x86_64-1_git`

mame2014-libretro will segfault if opening a rom from the command line without a full path.

Works:
* `retroarch -L /usr/lib64/libretro/mame2010_libretro.so ./alienar.zip`
* `retroarch -L /usr/lib64/libretro/mame2010_libretro.so roms/alienar.zip`
* Starting the game from the menu.

Segfault:
 * `retroarch -L /usr/lib64/libretro/mame2003_libretro.so alienar.zip`
```
Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x00007fffe7c24abe in running_machine::retro_loop (this=0x0)
    at src/emu/machine.c:422
422         if (!m_paused)
(gdb) bt
#0  0x00007fffe7c24abe in running_machine::retro_loop (this=0x0)
    at src/emu/machine.c:422
#1  0x00007fffe7c22be8 in retro_main_loop () at src/emu/mame.c:345
#2  0x00007fffe6dd983a in retro_run () at src/osd/retro/libretro.c:551
#3  0x00000000004127b6 in core_run () at core_impl.c:434
#4  0x0000000000426e68 in runloop_iterate (sleep_ms=0x7fffffffe0b0)
    at runloop.c:1183
#5  0x0000000000411337 in rarch_main (argc=4, argv=0x7fffffffe1c8, data=0x0)
    at frontend/frontend.c:130
#6  0x000000000041139e in main (argc=4, argv=0x7fffffffe1c8)
    at frontend/frontend.c:148
```
Full GDB log - http://pastebin.com/pdsZVYct

This works in mame2000-libretro, but mame2003-libretro and mame2010-libretro have similar issues.
https://github.com/libretro/mame2003-libretro/issues/74
https://github.com/libretro/mame2010-libretro/issues/25

**Comment by r-type** [comment]
yes we should check if not slash in path then we should add a ./

**Comment by orbea** [comment]
@r-type Hey, thanks, you just made my day!

I know these issues don't seem like much, but as someone who uses a terminal often its easy to reproduce and I now feel much more comfortable in providing a build script for mame2014 for slackbuilds.org knowing no one else in a similar position will run into it. :)

Also when you have a chance it would be greatly appreciated if you could look at the similar issue for mame2003 linked in the op.

**Comment by r-type** [comment]
Sorry but for 2003 I'm not admin on this core and the syntax is different so I let other people fix 2003
