### ISSUE TITLE
Symbols not exported for android versions < 5.0

### ISSUE THREAD

**Issue by andres-asm** [libretro/mame2014-libretro#4]
For some reason lately the builds don't work on android versions lesser than 5.0.
The same core works in a 5.0 / 5.1 device but on 4.4 when I select the core the name reads "No Core"

@r-type do you have any idea about what could be causing this?

**Comment by r-type** [comment]
It's surely toolchain issue , as i build with an NDK10 standalone tc (gcc 4.8 ) and it work fine on  an 4.4 device.

**Comment by andres-asm** [comment]
Ok. I'll try that one, the latest cores in the buildbot are built with 10e/gcc 4.8 can you give those a spin?
