### ISSUE TITLE
[windows]compiling problems-libflac issues

### ISSUE THREAD

**Issue by ghost** [libretro/mame2014-libretro#45]
-Error 1 received when compiling under msys2. 

-The last version available in buildbot repo is dated 11-30-2016(for ume2014, mame2014) and 9-10-2016 for mess2014. Since the linux ports are constantly updated(currently dated 1-30-2017), then there's probably an error with the windows port.

-a (very long...) compile from latest source in git causes this error....
https://gist.github.com/retro-wertz/5d0ccd40547f0eab454265adc1b4fa29

(libflac seems to be a modified 1.2.1 version compared to included libflac from older commits from nov 2016 and on latest mame_libretro.)

**Comment by r-type** [comment]
maybe you can try replace line 56 by
https://github.com/libretro/mame2014-libretro/blob/master/3rdparty/libflac/include/share/compat.h#L56
````
#if !defined(HAVE_FSEEKO) && !defined __MINGW32__
#define fseeko fseeko64
#define ftello ftello64
#endif
````

**Comment by ghost** [comment]
i commented those #defines before, but i also did your suggestion and have this:
https://gist.github.com/retro-wertz/d2bf1c3c47a7ebe6fb29fda05c4a422d

(im doing a target=mame subtarget=tiny for a quicker compile)

**Comment by r-type** [comment]
replace line 142 with
```` 
#if defined( _WIN32) && !defined(__MINGW32__)
````
if you confirm it build fine with the 2 above changes, a will commit fix.

**Comment by ghost** [comment]
it compiles now, mame2014 works ok. haven't have time to check mess2014 and ume2014 though.

**Comment by r-type** [comment]
thanks for reporting and testing ,now wait and see.

**Comment by ghost** [comment]
since the compile issue has been resolved and new builds are now being created in buildbot, then its safe to close this. just reopen if there are other compile issues.
