### ISSUE TITLE
Segfault using gcc 6.2

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/mame2014-libretro#47]
I'm getting segfault on mame2014 built with gcc 6.2 (ubuntu 16.10), when trying to run CPS-1/2, Neo Geo, Sega System 16B (goldnaxe) and Sega X Board (aburner2)

It's working with other games like captaven (deco32), sfex2p (sony  zn-2) and dkong

Workaround: build it with gcc 5 or clang.

I can't do a proper backtrace because #46

**Comment by r-type** [comment]
it's a know issue , GCC6.0 change default behavior .

https://github.com/libretro/mame2010-libretro/commit/0f020ca2b2db390949ac4a20eaf1f21b0848d52e

https://gcc.gnu.org/gcc-6/porting_to.html 
```
 When optimizing, GCC now assumes the this pointer can never be null, which is guaranteed by the language rules. Invalid programs which assume it is OK to invoke a member function through a null pointer (possibly relying on checks like this != NULL) may crash or otherwise fail at run time if null pointer checks are optimized away. With the -Wnull-dereference option the compiler tries to warn when it detects such invalid code.

If the program cannot be fixed to remove the undefined behavior then the option -fno-delete-null-pointer-checks can be used to disable this optimization. That option also disables other optimizations involving pointers, not only those involving this. 
```

So to be short fix the core to remove  the undefined behavior (best way as also stated Alcaro )
or (bad way) add -fno-delete-null-pointer-checks as we did in 2010 as it is time consuming to fix old core.

**Comment by sergiobenrocha2** [comment]
It's working now!
