### ISSUE TITLE
Add nagscreen and hiscore patches back to mame2014

### ISSUE THREAD

**Issue by OmegaXII** [libretro/mame2014-libretro#5]
Would it be possible to add the nagscreen and hiscore patches back to mame2014? I know they were removed to make it easier to pull updates from upstream mame, but this mame core won't be doing that anymore.

**Comment by Enverex** [comment]
The code already appears to be there still - https://github.com/libretro/mame2014-libretro/blob/master/src/emu/ui/ui.c - Look for show_warnings - so I can only assume it's disabled in the Core options, not within the core's own code as it all looks like it's still in place.

**Comment by Enverex** [comment]
Pull sent for hiding the nag/info screens - https://github.com/libretro/mame2014-libretro/pull/11

**Comment by sergiobenrocha2** [comment]
"Hide nag screen" is not working, seems it's ON always whatever I change this option.

Same problem to "Hide gameinfo screen" and "Hide warnings screen"

**Comment by Enverex** [comment]
Unfortunately I don't have a 2014 full set to test against. Does anyone have a stand-alone ROM that I can use to test this against?

**Comment by Enverex** [comment]
I'm getting reports that this works fine, are you sure you're using an updated version of this core and not an old one?

**Comment by sergiobenrocha2** [comment]
You can use the last rom set to test it. People are saying it's working because it's enabled all the time, whatever you set it ON or OFF heh

**Comment by Enverex** [comment]
Ok. I'll try it later and report back.

**Comment by inactive123** [comment]
Nag screen is a problem for Emscripten and for running it without libco in general, so I think we figured it was just best to just remove it altogether.

Unless you guys absolutely have to get it back again.

**Comment by sergiobenrocha2** [comment]
Ah ok, I think it's fine then. It's just odd to have those options yet, may we hide them for an while?

**Comment by Enverex** [comment]
I'm happy for it to be gone completely. I just made it an option as I believe that was the consensus at the time.
