### ISSUE TITLE
Problems Compiling Mame Libretro with Visual Studio 2015

### ISSUE THREAD

**Issue by godzil21** [libretro/mame2014-libretro#6]
I'm having problems trying to compile mame2014-libretro sources with Visual Studio for creating the symbols for debugging in Visual Studio.

With gcc I have no problem compiling but trying to compile with VS2015 with : 

make MSVC_BUILD=1 DEBUG=1 SYMBOLS=1 

 compiling crashes with error in  3rdParty library FLAC: 

error message:

**3rdparty/libflac/src/libFLAC/format.c:60:1: error: stray '\' in program
 FLAC_API const char *FLAC__VERSION_STRING  VERSION ;
 ^
3rdparty/libflac/src/libFLAC/format.c:60:1: error: missing terminating " character
3rdparty/libflac/src/libFLAC/format.c:66:1: error: stray '\' in program
 FLAC_API const char *FLAC__VENDOR_STRING = "reference libFLAC " VERSION " 20070917";
 ^
3rdparty/libflac/src/libFLAC/format.c:66:1: error: missing terminating " character
3rdparty/libflac/src/libFLAC/format.c:66:73: error: expected ',' or ';' before string constant
 FLAC_API const char *FLAC__VENDOR_STRING = "reference libFLAC " VERSION " 20070917";**
                                                                         ^

...any idea what's going on????  . BTW, I'm compiling in windows 7 64 bits .

Thanks a lot!

**Comment by Alcaro** [comment]
Suggested fix:

[3rdparty/libflac/build/config.mk:43](https://github.com/libretro/mame2014-libretro/blob/master/3rdparty/libflac/build/config.mk#L43). Remove backslashes.

Not tested, may break other platforms.

**Comment by godzil21** [comment]
Thanks a lot Alcaro!

Now with your suggestion the compilation have finished ok!!! Note that in line 66 with this modification I had to remove also two " between the word VERSION.

Moving on!

**Comment by Alcaro** [comment]
Let's keep this open until we fix it in the repo, okay?

**Comment by godzil21** [comment]
Sure! up  to you! ...Also would be very helpful to make again work the flags DEBUG and SYMBOLS in the Makefile instead of trying to modify the Makefile manually. Actually I'm modifying the code inserting printf for trying to see what is doing because the debugging is disabled... 

Regards!
