### ISSUE TITLE
Remove hack and have a proper fix for segfaults.

### ISSUE THREAD

**Issue by orbea** [libretro/mame2014-libretro#64]
This bandaid in commit https://github.com/libretro/mame2014-libretro/commit/49f55c15095cf67c93f4f6e8090f24d56c8e5a2b should go. It would be much better to supply a proper fix instead of silently hiding the behavior and closing still valid issues. Otherwise it will never be fixed.

See https://github.com/libretro/mame2014-libretro/issues/47.

**Comment by r-type** [comment]
So go on and fix all the null check pointer of this core if you have time. Myself i have no time to spend in.

**Comment by orbea** [comment]
If I knew how I would of already done so and when I do know how I will try to do so. :)

That said I think the first step is to not shove it under the rug so people can at least be aware of the workaround.

**Comment by orbea** [comment]
Would you mind pointing out where and how this can be fixed? If I'm given some pointers on fixing this I am willing to do the work. :)

**Comment by r-type** [comment]
You will have to remove all null check ptr in the code. There was an issue about it on old mame core. I cant find it now.i will link later

**Comment by orbea** [comment]
Thanks, I do think it would be good to see these older mame cores working as well as they can. :) Its gets harder and harder for me to use mame the newer it gets, the size requirement for roms alone is too much...

**Comment by r-type** [comment]
https://github.com/libretro/mame2010-libretro/commit/0f020ca2b2db390949ac4a20eaf1f21b0848d52e

the keys is the @Alcaro comment , maybe he can help you to done a proper fix. i can't help more here

**Comment by rb6502** [comment]
@orbea: there is no significant increase in the size requirement for ROMs as long as you only download ROMs for games you're interested in.
