### ISSUE TITLE
Problem loading mame games with compiled 64 bits windows libretro in retroarch...

### ISSUE THREAD

**Issue by godzil21** [libretro/mame2014-libretro#7]
Hi again!

It seems there is a problem compiling this version of libretro in windows 64. 

If I download the core from inside Retroarch (mame 2014) and load any rom Retroarch loads the game without any problems but **if I put in my cores directory directly my windows mingw compiled version and execute retroarch from the menu ,as before, or from the cmd with :  retroarch_debug.exe -L .\cores\mame2014_libretro.dll j:\retroarch_64\samerom.zip then only appears briefly the message of initializing and mame doesn't load any game...**

Also the size of the downloaded retroarch version of the core is : 95.252 KB and my compiled version is only 89.990 Kb so some libraries or data are lost in the compiled version. Any idea ? 

I execute the Makefile with  make (without any params) and finishes without any error.

Thanks a lot!

**Comment by godzil21** [comment]
Message deleted  because as says ToadKing was a mistake.The problem persists...

**Comment by ToadKing** [comment]
libwinpthread-1.dll is a library in many MinGW-based build environments and should never be installed directly into System32/SysWOW64, they should only be packaged with the program.

**Comment by godzil21** [comment]
Hi ToadKing!

I needed the libwinpthread-1.dll in system32/SysWOW64 because I was loading the core outside of the retroarch directory trying to create my own frontend ,I didn't want to create more copies of the library.The first message is valid.  I don't know if this has to do with the libco libraries and my windows being 64 bits...

**Comment by godzil21** [comment]
I have changed the issue title because I believe this explains a little better the problem...

**Comment by godzil21** [comment]
This issue can be closed now thanks to the helpful indications of Radius in the irc channel #retroarch . The problem was that my mingw toolchain used Seh compilation instead of SjLj exceptions so some issue related with the libco threads library was making the core crash . Now compiled with sljl exceptions the core works ok. I let this explanation here for any poor guy (like me) trying to compile this core in windows.
